trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - '*'

jobs:
- job: Build
  displayName: 'Build Job'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      echo 'Building the application...'
      # Add build commands here
    displayName: 'Build'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Build
  condition: succeeded('Build')
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      echo 'Deploying the application...'
      # Add deployment commands here
    displayName: 'Deploy'